apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jwjhb7dyk-python
  janus-idp.io/tekton: jwjhb7dyk-python
  backstage.io/kubernetes-id: jwjhb7dyk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jwjhb7dyk-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
