apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jwjhb7dyk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jwjhb7dyk-python 
  name: jwjhb7dyk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jwjhb7dyk-python 
